### ISSUE TITLE
Make analyse more robust regarding CLTS

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#30]
Currently the `bantugrollemund` dataset crashes when analyse is called with this:

```
ìɣʉ́ ˋ OrderedDict([('ID', '557'), ('Local_ID', None), ('Language_ID', 'njengrassfields'), ('Parameter_ID', 'eye'), ('Value', 'ìɣʉ́ ˋ'), ('Form', 'ìɣʉ́ ˋ'), ('Segments', ['ì', 'ɣ', 'ʉ́', '_ˋ']), ('Comment', None), ('Source', ['ALGABNjenGrassfields']), ('Cognacy', 'eye-3'), ('Loan', None)])
Traceback (most recent call last):
  File "/Users/simon/files/Projects/lexibank2018/pylexibank/src/pylexibank/commands/curate.py", line 74, in curate
    commands[user_input[0]](args)
  File "/Users/simon/files/Projects/lexibank2018/pylexibank/src/pylexibank/commands/curate.py", line 24, in <lambda>
    'analyze': lambda args: with_dataset(args, analyze),
  File "/Users/simon/files/Projects/lexibank2018/pylexibank/src/pylexibank/commands/util.py", line 25, in with_dataset
    func(get_dataset(args, dataset.id), **vars(args))
  File "/Users/simon/files/Projects/lexibank2018/pylexibank/src/pylexibank/commands/analyze.py", line 17, in analyze
    ds.write_json(dict(transcription=_analyze(ds)))
  File "/Users/simon/files/Projects/lexibank2018/pylexibank/src/pylexibank/commands/analyze.py", line 31, in _analyze
    ans, bad_words, invalid_words = test_sequences(dataset.cldf, model='dolgo')
  File "/Users/simon/files/Projects/lexibank2018/pylexibank/src/pylexibank/lingpy_util.py", line 116, in test_sequences
    row['Segments'], analysis=analysis, model=model)
  File "/Users/simon/files/Projects/lexibank2018/pylexibank/src/pylexibank/lingpy_util.py", line 67, in test_sequence
    bipa_analysis = [BIPA[s] for s in segments]
  File "/Users/simon/files/Projects/lexibank2018/pylexibank/src/pylexibank/lingpy_util.py", line 67, in <listcomp>
    bipa_analysis = [BIPA[s] for s in segments]
  File "/Users/simon/files/Projects/lexibank2018/env/lib/python3.6/site-packages/pyclts-0.1.0-py3.6.egg/pyclts/models.py", line 47, in __getitem__
    return self.resolve_sound(sound)
  File "/Users/simon/files/Projects/lexibank2018/env/lib/python3.6/site-packages/pyclts-0.1.0-py3.6.egg/pyclts/transcriptionsystem.py", line 282, in resolve_sound
    return self._parse(string)
  File "/Users/simon/files/Projects/lexibank2018/env/lib/python3.6/site-packages/pyclts-0.1.0-py3.6.egg/pyclts/transcriptionsystem.py", line 254, in _parse
    sound += base_sound.s
AttributeError: 'Marker' object has no attribute 's'
AttributeError: 'Marker' object has no attribute 's'
```

...which is failing because of the "ìɣʉ́ ˋ" form ([see also](https://github.com/cldf/clts/issues/110)).

This form should be fixed, I guess, but it would be nice if analyse worked and flagged this (and others as problematic)

**Comment by xrotwang** [comment]
The ` ` (space) is interpreted as marker. While I agree that pyclts should handle this in a better/more informative way, whitespace in input forms may be something that requires pre-processing. This is particularly important, if the dataset also uses orthography profiles which may introduce meaningful whitespace.
