### ISSUE TITLE
lexibank orthography doesn't work: AttributeError: 'Dataset' object has no attribute 'run'

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#76]
```
Traceback (most recent call last):
  File "/Users/simon/files/Projects/lexibank2018/env/bin/lexibank", line 11, in <module>
    load_entry_point('pylexibank', 'console_scripts', 'lexibank')()
  File "/Users/simon/projects/lexibank2018/pylexibank/src/pylexibank/__main__.py", line 128, in main
    sys.exit(parser.main())
  File "/Users/simon/files/Projects/lexibank2018/env/lib/python3.6/site-packages/clldutils/clilib.py", line 110, in main
    catch_all=catch_all, parsed_args=args)
  File "/Users/simon/files/Projects/lexibank2018/env/lib/python3.6/site-packages/clldutils/clilib.py", line 82, in main
    self.commands[args.command](args)
  File "/Users/simon/files/Projects/lexibank2018/env/lib/python3.6/site-packages/clldutils/clilib.py", line 35, in __call__
    return self.func(args)
  File "/Users/simon/projects/lexibank2018/pylexibank/src/pylexibank/commands/misc.py", line 112, in orthography
    for line in ds.run('lexemes'):
AttributeError: 'Dataset' object has no attribute 'run'
```

**Comment by SimonGreenhill** [comment]
...which should be replaced with  ```for row in self.cldf['FormTable']:```

however, do we want a convenience function  `iter_lexemes`?

**Comment by xrotwang** [comment]
I'm in the process of fixing this. As far as I can tell, the command is intended to seed an orthography profile from the raw data, so iterating over the CLDF output won't do.
