### ISSUE TITLE
Pinning pylexibank to  a specific version makes developing hard.

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#97]
Most of the released datasets pin pylexibank == 1.1.1, this has the side effect of making development difficult as this happens -- i.e. a failure because I have 1.2.0 installed:

```
Using configuration file at:
/Users/simon/Library/Application Support/pylexibank/config.ini

Traceback (most recent call last):
  File "/Users/simon/files/Projects/lexibank2018/env/bin/lexibank", line 11, in <module>
    load_entry_point('pylexibank', 'console_scripts', 'lexibank')()
  File "/Users/simon/projects/lexibank2018/pylexibank/src/pylexibank/__main__.py", line 139, in main
    sys.exit(parser.main())
  File "/Users/simon/projects/lexibank2018/env/lib/python3.6/site-packages/clldutils-2.6.3-py3.6.egg/clldutils/clilib.py", line 110, in main
    catch_all=catch_all, parsed_args=args)
  File "/Users/simon/projects/lexibank2018/env/lib/python3.6/site-packages/clldutils-2.6.3-py3.6.egg/clldutils/clilib.py", line 82, in main
    self.commands[args.command](args)
  File "/Users/simon/projects/lexibank2018/env/lib/python3.6/site-packages/clldutils-2.6.3-py3.6.egg/clldutils/clilib.py", line 35, in __call__
    return self.func(args)
  File "/Users/simon/projects/lexibank2018/pylexibank/src/pylexibank/commands/check.py", line 26, in check
    ds = get_dataset(args)
  File "/Users/simon/projects/lexibank2018/pylexibank/src/pylexibank/commands/util.py", line 11, in get_dataset
    for dataset in args.cfg.datasets:
  File "/Users/simon/projects/lexibank2018/env/lib/python3.6/site-packages/clldutils-2.6.3-py3.6.egg/clldutils/misc.py", line 203, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/Users/simon/projects/lexibank2018/pylexibank/src/pylexibank/__main__.py", line 85, in datasets
    key=lambda d: d.id)
  File "/Users/simon/projects/lexibank2018/pylexibank/src/pylexibank/dataset.py", line 702, in iter_datasets
    yield ep.load()(glottolog=glottolog, concepticon=concepticon)
  File "/Users/simon/files/Projects/lexibank2018/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2290, in load
    self.require(*args, **kwargs)
  File "/Users/simon/files/Projects/lexibank2018/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2307, in require
    items = working_set.resolve(reqs, env, installer)
  File "/Users/simon/files/Projects/lexibank2018/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pylexibank 1.1.2.dev0 (/Users/simon/projects/lexibank2018/pylexibank/src), Requirement.parse('pylexibank==1.1.1'))
```

... it's also somewhat impossible to figure out which dataset is failing.

**Comment by SimonGreenhill** [comment]
PR #97 commits the sin of a bare exception, but catches a wider range of import errors, to display the dataset name that's failing, and then re-raise.

**Comment by xrotwang** [comment]
Hm. Ok. So we might specify a minimum required pylexibank in setup.py, but
record the exact version the CLDF was compiled with in cldf-metadata.json.

I guess we really have to spell out the two ways in which pylexibank is
used explicitly, to explain why different versions for writing and reading
datasets make sense.

Simon J Greenhill <notifications@github.com> schrieb am So., 7. Juli 2019,
09:56:

**Comment by xrotwang** [comment]
Maybe we should adopt an R-like upgrade attitude here: the min pylexibank
specified in setup.py is the minimum of what the compiler of the cldf had
installed and the latest released version at the time of CLDF creation.

And the installed pylexibank is stored in the datasets metadata.

Robert Forkel <xrotwang@googlemail.com> schrieb am So., 7. Juli 2019, 10:15:

**Comment by xrotwang** [comment]
The basic idea with this policy would be that whenever something goes
wrong, upgrading pylexibank should help.

Robert Forkel <xrotwang@googlemail.com> schrieb am So., 7. Juli 2019, 10:20:

**Comment by SimonGreenhill** [comment]
Yes, I think that makes sense. If you want to recapture the version as it was, you need to install the version in metadata, otherwise the latest should be best.

**Comment by chrzyki** [comment]
Minimum data and `pylexibank` version in metadata sounds like a reasonable compromise. Sorry for the hassle, @SimonGreenhill. :)

**Comment by chrzyki** [comment]
So our consensus for now is: `pylexibank>=1.1.1` for the datasets is fine? If yes, I'd quickly update the datasets accordingly, but will wait with a release until the final polishing has been carried out (i.e. the things that came up in the last couple of days).

**Comment by xrotwang** [comment]
Yes, I think that's the consensus. Maybe we'll roll out pyexibank 1.2 within next week.

**Comment by xrotwang** [comment]
no pylexibank 1.2 - instead straight to 2.0 - with this issue resolved via re-releasing all datasets ...
